CREATE OR REPLACE PROCEDURE INSERTAR_ALMACENES
  (P_NOM IN ALMACENES.NOMBRE%TYPE,
   P_TEMP IN ALMACENES.TEMPERATURA%TYPE,
   P_ILUM IN ALMACENES.TIPOILUMINACION%TYPE,
   P_TIPO IN ALMACENES.TIPOCAMARA%TYPE) IS
BEGIN
  INSERT INTO ALMACENES(NOMBRE,TEMPERATURA,TIPOILUMINACION,TIPOCAMARA) 
  VALUES (P_NOM,P_TEMP,P_ILUM,P_TIPO);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_RECURSOS 
  (P_NOM IN RECURSOS.NOMBRE%TYPE,
   P_FORMQ IN RECURSOS.FORMULAQUIMICA%TYPE,
   P_FICHSEG IN RECURSOS.FICHASEGURIDAD%TYPE,
   P_UNI IN RECURSOS.UNIDADES%TYPE,
   P_CANT IN RECURSOS.CANTIDAD%TYPE,
   P_RESERV IN RECURSOS.RESERVAMINIMA%TYPE,
   P_TIPO IN RECURSOS.TIPO%TYPE,
   FK_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO RECURSOS(NOMBRE, FORMULAQUIMICA, FICHASEGURIDAD, UNIDADES, CANTIDAD, RESERVAMINIMA, TIPO, ALMACEN)
  VALUES (P_NOM, P_FORMQ, P_FICHSEG, P_UNI, P_CANT, P_RESERV, P_TIPO, FK_ALM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_POSICIONES 
  (OID_POS IN POSICIONES.ID_PS%TYPE,
   P_POS IN POSICIONES.POSICION%TYPE,
   P_REC IN RECURSOS.NOMBRE%TYPE,
   P_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO POSICIONES(ID_PS,POSICION,RECURSO,ALMACEN)
  VALUES (OID_POS,P_POS,P_REC,P_ALM);
END;
/

CREATE OR REPLACE PROCEDURE INSERTAR_TEMP_AMB 
  (OID_TA IN TEMPERATURA_AMBIENTE.ID_TA%TYPE,
   P_NOMB IN TEMPERATURA_AMBIENTE.NOMBRE%TYPE,
   P_TIPO IN TEMPERATURA_AMBIENTE.TIPO%TYPE,
   FK_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO TEMPERATURA_AMBIENTE(ID_TA,NOMBRE,TIPO,ALMACEN)
  VALUES (OID_TA,P_NOMB,P_TIPO,FK_ALM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_EQU_FR 
  (OID_EF IN EQUIPOS_FRIO.ID_EF%TYPE,
   P_NOMB IN EQUIPOS_FRIO.NOMBRE%TYPE,
   P_TEMP IN EQUIPOS_FRIO.TEMPERATURA%TYPE,
   FK_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO EQUIPOS_FRIO(ID_EF,NOMBRE,TEMPERATURA,ALMACEN)
  VALUES (OID_EF,P_NOMB,P_TEMP,FK_ALM);
 -- UPDATE PRESTAMOS SET FECHA_PREVISTA = P_FEC_PRE
 -- WHERE OID_PRESTAMO = FK_PRE;
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_AVISOS 
  (OID_AV IN AVISOS.ID_AV%TYPE,
   P_MENS IN AVISOS.MENSAJE%TYPE,
   FK_REC IN RECURSOS.NOMBRE%TYPE,
   FK_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO AVISOS(ID_AV,MENSAJE,RECURSO,ALMACEN)
  VALUES (OID_AV,P_MENS,FK_REC,FK_ALM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_RESPON_COMPRA 
  (OID_RC IN RESPONSABLES_COMPRA.ID_RC%TYPE,
   P_NOMB IN RESPONSABLES_COMPRA.NOMBRE%TYPE,
   P_EM IN RESPONSABLES_COMPRA.EMAIL%TYPE) IS
BEGIN
  INSERT INTO RESPONSABLES_COMPRA(ID_RC, NOMBRE, EMAIL)
  VALUES (OID_RC,P_NOMB,P_EM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_PEDIDOS 
  (OID_PD IN PEDIDOS.ID_PD%TYPE,
   FK_MENS IN AVISOS.ID_AV%TYPE,
   FK_PRO IN PROVEEDORES.ID_PR%TYPE,
   FK_RC IN RESPONSABLES_COMPRA.ID_RC%TYPE) IS
BEGIN
  INSERT INTO PEDIDOS(ID_PD, MENSAJE, PROVEEDOR, RESPONSABLECOMPRA)
  VALUES (OID_PD,FK_MENS,FK_PRO,FK_RC);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_PROVEEDORES 
  (P_EMP IN PROVEEDORES.NOMBREEMPRESA%TYPE,
   P_COM IN PROVEEDORES.NOMBRECOMERCIAL%TYPE,
   P_EM IN PROVEEDORES.EMAIL%TYPE) IS
BEGIN
  INSERT INTO PROVEEDORES(NOMBREEMPRESA,NOMBRECOMERCIAL,EMAIL)
  VALUES (P_EMP,P_COM,P_EM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_TELEFONOS 
  (P_TF IN TELEFONOS.TELEFONO%TYPE,
   FK_PRO IN PROVEEDORES.ID_PR%TYPE) IS
BEGIN
  INSERT INTO TELEFONOS(TELEFONO,PROVEEDOR)
  VALUES (P_TF,FK_PRO);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_USUARIO 
  (P_NOM IN USUARIOS.NOMBRE%TYPE,
   P_PASS IN USUARIOS.PASS%TYPE,
   P_EMAIL IN USUARIOS.EMAIL%TYPE,
   P_TIPO IN USUARIOS.TIPO%TYPE) IS
BEGIN
  INSERT INTO USUARIOS(NOMBRE, PASS, EMAIL, TIPO)
  VALUES (P_NOM, P_PASS, P_EMAIL, P_TIPO);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_PROV_REC 
  (FK_PR IN PROVEEDORES.ID_PR%TYPE,
   FK_REC IN RECURSOS.NOMBRE%TYPE,
   FK_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO PROVEEDORES_RECURSOS(PROVEEDOR,RECURSO,ALMACEN)
  VALUES (FK_PR,FK_REC,FK_ALM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_AV_RES
  (FK_RC IN RESPONSABLES_COMPRA.ID_RC%TYPE,
   FK_AV IN AVISOS.ID_AV%TYPE) IS
BEGIN
  INSERT INTO AVISOS_RESPONSABLE(RESPONSABLE,AVISO)
  VALUES (FK_RC,FK_AV);
END;
/