CREATE OR REPLACE PROCEDURE INSERTAR_ALMACENES
  (P_NOM IN ALMACENES.NOMBRE%TYPE,
   P_TEMP IN ALMACENES.TEMPERATURA%TYPE,
   P_ILUM IN ALMACENES.TIPOILUMINACION%TYPE,
   P_TIPO IN ALMACENES.TIPOCAMARA%TYPE) IS
BEGIN
  INSERT INTO ALMACENES(NOMBRE,TEMPERATURA,TIPOILUMINACION,TIPOCAMARA) 
  VALUES (P_NOM,P_TEMP,P_ILUM,P_TIPO);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_RECURSOS 
  (P_NOM IN RECURSOS.NOMBRE%TYPE,
   P_FORMQ IN RECURSOS.FORMULAQUIMICA%TYPE,
   P_FICHSEG IN RECURSOS.FICHASEGURIDAD%TYPE,
   P_UNI IN RECURSOS.UNIDADES%TYPE,
   P_CANT IN RECURSOS.CANTIDAD%TYPE,
   P_RESERV IN RECURSOS.RESERVAMINIMA%TYPE,
   P_TIPO IN RECURSOS.TIPO%TYPE,
   FK_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO RECURSOS(NOMBRE, FORMULAQUIMICA, FICHASEGURIDAD, UNIDADES, CANTIDAD, RESERVAMINIMA, TIPO, ALMACEN)
  VALUES (P_NOM, P_FORMQ, P_FICHSEG, P_UNI, P_CANT, P_RESERV, P_TIPO, FK_ALM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_POSICIONES 
  (OID_POS IN POSICIONES.OID_PS%TYPE,
   P_POS IN POSICIONES.POSICION%TYPE,
   P_REC IN RECURSOS.NOMBRE%TYPE,
   P_ALM IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO POSICIONES(OID_POS,P_POS,P_REC,P_ALM)
  VALUES (OID_POS,P_POS,P_REC,P_ALM);
END;
/
---
CREATE OR REPLACE PROCEDURE INSERTAR_PRESTAMO 
  (P_FEC IN PRESTAMOS.FECHA%TYPE,
   P_FEC_PRE IN PRESTAMOS.FECHA_PREVISTA%TYPE,
   FK_LIB IN PRESTAMOS.OID_LIBRO%TYPE,
   FK_USU IN PRESTAMOS.OID_USUARIO%TYPE) IS
BEGIN
  INSERT INTO PRESTAMOS(FECHA,FECHA_PREVISTA,OID_LIBRO,OID_USUARIO)
  VALUES (P_FEC,P_FEC_PRE,FK_LIB,FK_USU);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_RENOVACION 
  (P_FEC IN RENOVACIONES.FECHA%TYPE,
   P_FEC_PRE IN PRESTAMOS.FECHA_PREVISTA%TYPE,
   FK_PRE IN RENOVACIONES.OID_PRESTAMO%TYPE) IS
BEGIN
  INSERT INTO RENOVACIONES(FECHA,OID_PRESTAMO)
  VALUES (P_FEC,FK_PRE);
  UPDATE PRESTAMOS SET FECHA_PREVISTA = P_FEC_PRE
  WHERE OID_PRESTAMO = FK_PRE;
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_DEVOLUCION 
  (P_FEC IN DEVOLUCIONES.FECHA%TYPE,
   FK_PRE IN DEVOLUCIONES.OID_PRESTAMO%TYPE) IS
BEGIN
  INSERT INTO DEVOLUCIONES(FECHA,OID_PRESTAMO)
  VALUES (P_FEC,FK_PRE);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_USUARIO 
  (P_NIF IN USUARIOS.NIF%TYPE,
   P_NOM IN USUARIOS.NOMBRE%TYPE,
   P_APE IN USUARIOS.APELLIDOS%TYPE,
   P_DIR IN USUARIOS.DIRECCION%TYPE,
   P_MUN IN USUARIOS.OID_MUNICIPIO%TYPE,
   P_FECHA_NAC IN USUARIOS.FECHA_NACIMIENTO%TYPE,
   P_EMAIL IN USUARIOS.EMAIL%TYPE,
   P_PASS IN USUARIOS.PASS%TYPE,
   P_PERFIL IN USUARIOS.PERFIL%TYPE
   ) IS
BEGIN
  INSERT INTO USUARIOS(NIF, NOMBRE,APELLIDOS,DIRECCION,OID_MUNICIPIO, FECHA_NACIMIENTO, EMAIL, PASS, PERFIL)
  VALUES (P_NIF,P_NOM,P_APE,P_DIR,P_MUN, P_FECHA_NAC, P_EMAIL, P_PASS, P_PERFIL);
END;
/
create or replace PROCEDURE INSERTAR_GENERO_USUARIO 
  (FK_GEN IN GENEROS.OID_GENERO%TYPE,
   FK_USU IN USUARIOS.NIF%TYPE) IS
  oid_user USUARIOS.OID_USUARIO%type; 
--  oid_genre GENEROS.OID_GENERO%type;
BEGIN
	SELECT OID_USUARIO INTO oid_user FROM USUARIOS WHERE NIF = FK_USU;
	--SELECT OID_GENERO INTO oid_genre FROM GENEROS WHERE NOMBRE = FK_GEN;
	
    INSERT INTO GENEROSUSUARIOS(GENERO,USUARIO)
  	VALUES (FK_GEN,oid_user);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_GENERO
  (P_NOM IN GENEROS.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO GENEROS(NOMBRE)
  VALUES (P_NOM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_PROVINCIA 
  (P_NOM IN PROVINCIAS.NOMBRE%TYPE) IS
BEGIN
  INSERT INTO PROVINCIAS(NOMBRE)
  VALUES (P_NOM);
END;
/
CREATE OR REPLACE PROCEDURE INSERTAR_MUNICIPIO 
  (P_NOM IN MUNICIPIOS.NOMBRE%TYPE,
   P_PRO IN MUNICIPIOS.OID_PROVINCIA%TYPE) IS
BEGIN
  INSERT INTO MUNICIPIOS(NOMBRE,OID_PROVINCIA)
  VALUES (P_NOM,P_PRO);
END;
/
CREATE OR REPLACE PROCEDURE QUITAR_LIBRO (OID_LIBRO_A_QUITAR IN LIBROS.OID_LIBRO%TYPE) AS
  NUM_PRESTAMOS NUMBER;
BEGIN
  SELECT COUNT(*) INTO NUM_PRESTAMOS FROM PRESTAMOS WHERE PRESTAMOS.OID_LIBRO = OID_LIBRO_A_QUITAR;
  
  IF (NUM_PRESTAMOS <> 0) THEN
    RAISE_APPLICATION_ERROR(-20600,'No se puede quitar el libro porque ya tiene pr�stamos asignados');
  ELSE
    DELETE FROM AUTORIAS WHERE OID_LIBRO = OID_LIBRO_A_QUITAR;
    DELETE FROM LIBROS WHERE OID_LIBRO = OID_LIBRO_A_QUITAR;
  END IF;
END;
/
CREATE OR REPLACE PROCEDURE MODIFICAR_TITULO 
(OID_LIBRO_A_MOD IN LIBROS.OID_LIBRO%TYPE,
 TIT_LIBRO_A_MOD IN LIBROS.TITULO%TYPE) IS
BEGIN
  UPDATE LIBROS SET TITULO=TIT_LIBRO_A_MOD
  WHERE OID_LIBRO = OID_LIBRO_A_MOD;
END;
/
CREATE OR REPLACE PROCEDURE MODIFICAR_USUARIO 
(OID_USU_A_MOD IN USUARIOS.OID_USUARIO%TYPE,
 NOM_USU_A_MOD IN USUARIOS.NOMBRE%TYPE,
 APE_USU_A_MOD IN USUARIOS.APELLIDOS%TYPE,
 DIR_USU_A_MOD IN USUARIOS.DIRECCION%TYPE,
 OID_MUNI_A_MOD IN USUARIOS.OID_MUNICIPIO%TYPE) IS
BEGIN
  UPDATE USUARIOS
  SET NOMBRE=NOM_USU_A_MOD, APELLIDOS=APE_USU_A_MOD, 
	DIRECCION=DIR_USU_A_MOD, OID_MUNICIPIO=OID_MUNI_A_MOD
  WHERE OID_USUARIO = OID_USU_A_MOD;
END;