CREATE OR REPLACE PROCEDURE QUITAR_RECURSO 
(NOMBRE_A_MOD IN RECURSOS.NOMBRE%TYPE,
ALMACEN_A_MOD IN RECURSOS.ALMACEN%TYPE) AS
NUM_UNI NUMBER;
BEGIN
  SELECT UNIDADES INTO NUM_UNI FROM RECURSOS WHERE NOMBRE = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
  
  IF (NUM_UNI > 0) THEN
    RAISE_APPLICATION_ERROR(-20600,'No se puede quitar el libro porque todavía le quedan unidades');
  ELSE
    DELETE FROM RECURSOS WHERE NOMBRE = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
    DELETE FROM PROVEEDORES_RECURSOS WHERE RECURSO = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
    DELETE FROM POSICIONES WHERE RECURSO = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
  END IF;
END;
/