CREATE OR REPLACE PROCEDURE QUITAR_RECURSO 
(NOMBRE_A_MOD IN RECURSOS.NOMBRE%TYPE,
ALMACEN_A_MOD IN RECURSOS.ALMACEN%TYPE) IS
BEGIN
    DELETE FROM PROVEEDORES_RECURSOS WHERE RECURSO = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
    DELETE FROM POSICIONES WHERE RECURSO = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
    DELETE FROM RECURSOS WHERE NOMBRE = NOMBRE_A_MOD AND ALMACEN = ALMACEN_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE QUITAR_ALMACENES
(NOMBRE_A_MOD IN ALMACENES.NOMBRE%TYPE) IS
BEGIN
    DELETE FROM RECURSOS WHERE ALMACEN = NOMBRE_A_MOD;
    DELETE FROM EQUIPOS_FRIO WHERE ALMACEN = NOMBRE_A_MOD;
    DELETE FROM ALMACENES WHERE NOMBRE = NOMBRE_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE QUITAR_PROVEEDOR
(NOMBRE_A_MOD IN PROVEEDORES.ID_PR%TYPE) IS
BEGIN
    DELETE FROM PEDIDOS WHERE PROVEEDOR = NOMBRE_A_MOD;
    DELETE FROM PROVEEDORES_RECURSOS WHERE PROVEEDOR = NOMBRE_A_MOD;
    DELETE FROM PROVEEDORES WHERE ID_PR = NOMBRE_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE QUITAR_EQUIPOS_FRIO
(NOMBRE_A_MOD IN EQUIPOS_FRIO.ID_EF%TYPE) IS
BEGIN
    DELETE FROM EQUIPOS_FRIO WHERE ID_EF = NOMBRE_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE QUITAR_TEMPERATURA_AMBIENTE
(NOMBRE_A_MOD IN TEMPERATURA_AMBIENTE.ID_TA%TYPE) IS
BEGIN
    DELETE FROM TEMPERATURA_AMBIENTE WHERE ID_TA = NOMBRE_A_MOD;
END;
/

CREATE OR REPLACE PROCEDURE QUITAR_USUARIO
(NOMBRE_A_MOD IN USUARIOS.NOMBRE%TYPE) IS
BEGIN
    DELETE FROM USUARIOS WHERE NOMBRE = NOMBRE_A_MOD;
END;
/