DECLARE
OID_PROV_ACME INTEGER;
OID_PROV_935 INTEGER;

BEGIN

INSERTAR_PROVEEDORES('ACME', 'Paco', 'acme@gmail.com');
SELECT SEC_PROVEEDORES.CURRVAL INTO OID_PROV_ACME FROM DUAL;

INSERTAR_PROVEEDORES('935', 'Maxis', 'maxis@gmail.com');
SELECT SEC_PROVEEDORES.CURRVAL INTO OID_PROV_935 FROM DUAL;

COMMIT;

END;