DECLARE
OID_AMB_1 INTEGER;
OID_EQUP_1 INTEGER;
OID_AMB_2 INTEGER;
OID_EQUP_2 INTEGER;

BEGIN

INSERTAR_TEMP_AMB('Estanteria A', 'Estanteria', 'Sotano');
SELECT SEC_TEMPERATURA.CURRVAL INTO OID_AMB_1 FROM DUAL;

INSERTAR_EQU_FR('Frigorifico 1', '2', 'Invernadero');
SELECT SEC_EQUIPOS.CURRVAL INTO OID_EQUP_1 FROM DUAL;

INSERTAR_TEMP_AMB('Cajonera A', 'Cajonera', 'Invernadero');
SELECT SEC_TEMPERATURA.CURRVAL INTO OID_AMB_2 FROM DUAL;

INSERTAR_EQU_FR('Frigorifico 2', '-10', 'Sotano');
SELECT SEC_EQUIPOS.CURRVAL INTO OID_EQUP_2 FROM DUAL;

COMMIT;

END;