DECLARE

OID_AMB_1 INTEGER;
OID_EQUP_1 INTEGER;
OID_AMB_2 INTEGER;
OID_EQUP_2 INTEGER;

OID_TEF_ACME INTEGER;
OID_TEF_935 INTEGER;

OID_POS_CS INTEGER;
OID_POS_AC INTEGER;
OID_POS_AS INTEGER;
OID_POS_AN INTEGER;
OID_POS_HM INTEGER;
OID_POS_F1 INTEGER;
OID_POS_F2 INTEGER;
OID_POS_F3 INTEGER;
OID_POS_F4 INTEGER;
OID_POS_F5 INTEGER;
OID_POS_M1 INTEGER;
OID_POS_M2 INTEGER;
OID_POS_M3 INTEGER;
OID_POS_M4 INTEGER;
OID_POS_M5 INTEGER;

BEGIN

INSERTAR_TEMP_AMB('Estanteria A', 'Estanteria', 'Sótano');
SELECT SEC_TEMPERATURA.CURRVAL INTO OID_AMB_1 FROM DUAL;

INSERTAR_EQU_FR('Frigorífico 1', '2', 'Invernadero');
SELECT SEC_EQUIPOS.CURRVAL INTO OID_EQUP_1 FROM DUAL;

INSERTAR_TEMP_AMB('Cajonera A', 'Cajonera', 'Invernadero');
SELECT SEC_TEMPERATURA.CURRVAL INTO OID_AMB_2 FROM DUAL;

INSERTAR_EQU_FR('Frigorífico 2', '-10', 'Sótano');
SELECT SEC_EQUIPOS.CURRVAL INTO OID_EQUP_2 FROM DUAL;


INSERTAR_TELEFONOS('924303113', '1');
SELECT SEC_TELEFONOS.CURRVAL INTO OID_TEF_ACME FROM DUAL;

INSERTAR_TELEFONOS('678921562', '2');
SELECT SEC_TELEFONOS.CURRVAL INTO OID_TEF_935 FROM DUAL;

INSERTAR_TELEFONOS('931935115', '2');
SELECT SEC_TELEFONOS.CURRVAL INTO OID_TEF_935 FROM DUAL;


INSERTAR_PROV_REC('1','Cloruro de sodio','Sótano');

INSERTAR_PROV_REC('1','Ácido clorhídrico','Cámara Frigorífica A');

INSERTAR_PROV_REC('1','Ácido sulfúrico','Sótano');

INSERTAR_PROV_REC('1','Ácido nítrico','Cámara Frigorífica A');

INSERTAR_PROV_REC('2','Hidróxido de magnesio','Sótano');

INSERTAR_PROV_REC('2','Fungible 1','Sótano');

INSERTAR_PROV_REC('2','Fungible 2','Sótano');

INSERTAR_PROV_REC('2','Fungible 3','Sótano');

INSERTAR_PROV_REC('2','Fungible 4','Sótano');

INSERTAR_PROV_REC('2','Fungible 5','Sótano');


INSERTAR_POSICIONES('2B','Cloruro de sodio','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_CS FROM DUAL;

INSERTAR_POSICIONES('1C','Ácido clorhídrico','Cámara Frigorífica A');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_AC FROM DUAL;

INSERTAR_POSICIONES('1B','Ácido sulfúrico','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_AS FROM DUAL;

INSERTAR_POSICIONES('2C','Ácido nítrico','Cámara Frigorífica A');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_AN FROM DUAL;

INSERTAR_POSICIONES('1D','Hidróxido de magnesio','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_HM FROM DUAL;

INSERTAR_POSICIONES('2D','Fungible 1','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_F1 FROM DUAL;

INSERTAR_POSICIONES('3D','Fungible 2','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_F2 FROM DUAL;

INSERTAR_POSICIONES('4D','Fungible 3','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_F3 FROM DUAL;

INSERTAR_POSICIONES('5D','Fungible 4','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_F4 FROM DUAL;

INSERTAR_POSICIONES('6D','Fungible 5','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_F5 FROM DUAL;

INSERTAR_POSICIONES('1F','Material 1','Invernadero');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_M1 FROM DUAL;

INSERTAR_POSICIONES('1F','Material 2','Sótano');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_M2 FROM DUAL;

INSERTAR_POSICIONES('2F','Material 3','Invernadero');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_M3 FROM DUAL;

INSERTAR_POSICIONES('3F','Material 4','Cámara in-vitro');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_M4 FROM DUAL;

INSERTAR_POSICIONES('4F','Material 5','Cámara in-vitro');
SELECT SEC_POSICIONES.CURRVAL INTO OID_POS_M5 FROM DUAL;

COMMIT;

END;