DECLARE
OID_PROV_ACME INTEGER;
OID_PROV_935 INTEGER;

BEGIN

INSERTAR_PROVEEDORES('ACME', 'Paco', 'acme@gmail.com');
SELECT SEC_PROVEEDORES.CURRVAL INTO OID_PROV_ACME FROM DUAL;

INSERTAR_PROVEEDORES('935', 'Maxis', 'maxis@gmail.com');
SELECT SEC_PROVEEDORES.CURRVAL INTO OID_PROV_935 FROM DUAL;

COMMIT;

END;

DECLARE
OID_TEF_ACME INTEGER;
OID_TEF_935 INTEGER;

BEGIN

INSERTAR_TELEFONOS('99999999', '1');
SELECT SEC_TELEFONOS.CURRVAL INTO OID_TEF_ACME FROM DUAL;

INSERTAR_TELEFONOS('931935', '2');
SELECT SEC_TELEFONOS.CURRVAL INTO OID_TEF_935 FROM DUAL;

INSERTAR_TELEFONOS('931935115', '2');
SELECT SEC_TELEFONOS.CURRVAL INTO OID_TEF_935 FROM DUAL;

COMMIT;

END;